<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>bke-updater-core</AssemblyName>
    <RootNamespace>BKE.LicensingAgent.Updater</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../BKE.LicensingAgent.Storage/BKE.LicensingAgent.Storage.csproj" />
  </ItemGroup>
</Project>
