<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>BKE.LicensingAgent.StandaloneAcquisitionCertification</AssemblyName>
    <RootNamespace>BKE.LicensingAgent.StandaloneAcquisitionCertification</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/BKE.LicensingAgent.Application/BKE.LicensingAgent.Application.csproj" />
    <ProjectReference Include="../../src/BKE.LicensingAgent.Infrastructure/BKE.LicensingAgent.Infrastructure.csproj" />
  </ItemGroup>
</Project>
